name: Production

on:
  release:
    types: [published]

jobs:
  deploy:
    name: Deploy
    uses: ./.github/workflows/deploy-template.yml
    with:
      subdir: ${GITHUB_REF/refs\/tags\/v/}
      subdir_header: "Cache-Control:no-store"
