name: Release

on:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  release:
    name: Auto release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"

      - name: Install
        run: npm ci --ignore-scripts

      - name: setup git
        run: |
          git config --global user.name "github-bot[bot]"
          git config --global user.email "github-bot@github.com"

      - name: Extract version
        id: extract_version
        uses: Saionaro/extract-package-version@v1.2.1

      - name: Print version
        run: echo ${{ steps.extract_version.outputs.version }}

      - name: Push tag
        run: |
          git tag -a v${{ steps.extract_version.outputs.version }} -m "v${{ steps.extract_version.outputs.version }}"
          git push origin v${{ steps.extract_version.outputs.version }}

      - name: Publish GH release
        run: npx changelogen gh release --token ${{ secrets.GITHUB_TOKEN }}

      - name: Merge main back to develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: main
          target_branch: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Merge main into develop

